### ISSUE TITLE
About crawler config.cfg

### ISSUE THREAD

**Issue by rascal-3** [thetatoken/theta-infrastructure-ledger-explorer#10]
Hi,

I'm running theta-protocol-ledger for mainnet,
and I would like to run theta-infrastructure-ledger-explorer crawler too.

I edited backend/crawler/config.cfg like this:

```
{
    "mongo": {
        "address": "localhost",
        "port": 27017,
        "dbName": "theta_mainnet"
    },
    "node": {
        "address": "localhost",
        "port": 16888
    },
    "log": {
        "level": "debug"
    },
    "blockchain": {
        "network_id": "mainnet"
    },
    "accounting": {
        "coinmarketcap_api_key": "MY_MARKETCAP_API_KEY_STRING",
        "wallet_addresses": [
            "2416",
            "3822"
        ]
    }
}
```

And now, I got many following errors, and can accumulate only a few transaction data:

```
9/2/2020, 12:02:39 PM[log] Loading config file: config.cfg
9/2/2020, 12:02:39 PM[log] [object Object]
url is:  mongodb://localhost:27017/theta_mainnet
9/2/2020, 12:02:39 PM[log] Mongo DB connection succeeded
9/2/2020, 12:02:40 PM[log] Initializng progress record..
9/2/2020, 12:02:40 PM[log] Loading initial accounts file: theta-balance-height.json
9/2/2020, 12:02:41 PM[log] Start a new crawler progress
9/2/2020, 12:02:41 PM[log] DB transaction count progress: 0
9/2/2020, 12:02:41 PM[log] crawled_block_height_progress:  0
.............
9/2/2020, 4:23:34 AM[log]crawled_block_height_progress:  0
9/2/2020, 4:23:34 AM[log]Number of upsert PENDING transactions: 1
9/2/2020, 4:23:34 AM[log]Latest block height: 7157078
9/2/2020, 4:23:34 AM[log]DB block height progress: 0
9/2/2020, 4:23:34 AM[error]Cannot read property 'length' of undefined | stack: TypeError: Cannot read property 'length' of undefined
    at /home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/jobs/read-block.js:155:53
    at tryCatcher (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js
:512:31)
    at Promise._settlePromise (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
9/2/2020, 4:23:35 AM[log]Start a new crawler progress
9/2/2020, 4:23:35 AM[log]DB transaction count progress: 0
9/2/2020, 4:23:35 AM[log]crawled_block_height_progress:  0
9/2/2020, 4:23:36 AM[log]Number of upsert PENDING transactions: 2
9/2/2020, 4:23:36 AM[log]Latest block height: 7157078
9/2/2020, 4:23:36 AM[log]DB block height progress: 0
9/2/2020, 4:23:36 AM[error]Cannot read property 'length' of undefined | stack: TypeError: Cannot read property 'length' of undefined
    at /home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/jobs/read-block.js:155:53
    at tryCatcher (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js
:512:31)
    at Promise._settlePromise (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/rascal/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

<img width="1276" alt="Screenshot 2020-09-02 17 48 18" src="https://user-images.githubusercontent.com/5564192/91960689-2e16e480-ed45-11ea-9eda-9895fb675307.png">

Is my config.cfg wrong?

Thank you.

Best Regards,
Rascal

**Comment by zhenyang-sliver** [comment]
Hi Rascal,

Your config file looks good, the issue is that your local theta node doesn't contain the block info from height 1. You can change the height in progress collection manually to the snapshot height on your theta node using the following commands in command line.
```
mongo
use theta_mainnet
db.progress.update({_id: “mainnet” }, {$set:{lst_blk_height: snapshot_height_on_your_theta_node}})
exit
```
Then you can rerun the crawler and it should work.
Let us know if there's any other issues.

Thanks,
Zhenyang

**Comment by rascal-3** [comment]
Hello Thenyan,

Thank you!
The errors gone and I can get data now!

<img width="1278" alt="Screenshot 2020-09-03 14 56 36" src="https://user-images.githubusercontent.com/5564192/92076924-6b877a80-edf6-11ea-9407-0eaba0651373.png">

However, data before the specified block height cannot be obtained, right?

If I skipped download latest snapshot as written in this page, can I get full archive node?
-> https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/mainnet.md#step-1-setup

Thank you again,
Rascal

**Comment by jieyilong** [comment]
You can use the **snapshot** file under this folder, then the node should download all the blocks starting from the genesis. It might take a while though to fully sync with the network though:

https://github.com/thetatoken/theta-protocol-ledger/tree/master/integration/mainnet/walletnode

**Comment by rascal-3** [comment]
Hi Jieyi,

Now it starts from block height 1!

<img width="1030" alt="Screenshot 2020-09-05 3 26 04" src="https://user-images.githubusercontent.com/5564192/92274279-e603e780-ef27-11ea-8378-c228ecee7796.png">

I should have seen theta-protocol-ledger's repository well...

Thanks a lot!!
Rascal

**Comment by rascal-3** [comment]
I'm gonna close this issue.

Thank you guys again!!

**Comment by giovannirco** [comment]
@rascal-3 how did you manage to sync the node from block 1 so fast?
