### ISSUE TITLE
About config.cfg Mongo Authentication and Redis version

### ISSUE THREAD

**Issue by giovannirco** [thetatoken/theta-infrastructure-ledger-explorer#17]
How can I authenticate to MongoDB with an username and password? I am currently using DocumentDB from AWS and was hopping to set the credentials to connect to it but I don't see a predefined option for that on config.cfg. 
Is there a way I can use an environment variable to set this information? That would be ideal for my setup running on a kubernetes cluster

I am also wondering what redis version I can use with the explorer? I see family set to 4 but I wanted to know if I can use Redis 5 on this project

**Comment by giovannirco** [comment]
I saw a commit from @zhenyang-sliver adding the URI entry in the config file so I tried this on my environment and it worked :tada: but I ran into a issue after successfully connecting to the DocDB, the error is similar but not the same as the error describe on #10 
One of the solutions was set the start_height to what the snapshot has but since I wanted the full history I have followed the steps described in the issue and started the node from scratch. When initialising the crawler I get the following error:

```
5/6/2021, 2:34:23 AM[log] Loading config file: config.cfg
5/6/2021, 2:34:23 AM[log] {"mongo":{"uri":"mongodb://thetaexplorer:<DocDB_password>@DocDB_hostname:27017","port":27017,"dbName":"theta-explorer"},"node":{"address":"theta-0.theta.coin-nodes.svc.cluster.local","port":16888},"log":{"level":"debug"},"blockchain":{"network_id":"mainnet"},"accounting":{"coinmarketcap_api_key":"COINMARKETCAP_API_KEY","wallet_addresses":["2416","3822"]},"redis":{"enabled":true,"isCluster":false,"host":"theta-explorer-redis-hostname","port":6379,"family":4,"db":0}}
redisConfig: {
  enabled: true,
  isCluster: false,
  host: 'theta-explorer-redis-hostname',
  port: 6379,
  family: 4,
  db: 0
}
url is:  mongodb://thetaexplorer:<DocDB_password>@<DocDB_hostname>:27017
(node:273) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
rest api running on port. 8080
connected to Redis
5/6/2021, 2:34:24 AM[log] Mongo DB connection succeeded
/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/utils.js:668
          throw error;
          ^

TypeError: Cannot read property 'length' of undefined
    at /home/node/theta-infrastructure-ledger-explorer/backend/mongo-db/active-account-dao.js:20:22
    at /home/node/theta-infrastructure-ledger-explorer/backend/mongo-db/mongo-client.js:159:14
    at /home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/utils.js:665:9
    at handleCallback (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/utils.js:102:55)
    at /home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/cursor.js:834:20
    at /home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/core/cursor.js:736:9
    at done (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/core/cursor.js:458:7)
    at /home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/core/cursor.js:533:11
    at executeCallback (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
    at callbackWithRetry (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/operations/execute_operation.js:122:14)
    at /home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/mongodb/lib/core/connection/pool.js:405:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Couldn't find the program running
```

The node still didn't fully sync with the blockchain, but I was having this exact same error before so I am not sure if I am doing something wrong or just need to wait the node to fully sync

This is my config.cfg file
```
{
    "mongo": {
        "uri": "__THETACLIARG_MONGO_URI__",
        "port": 27017,
        "dbName": "theta-explorer"
    },
    "node": {
        "address": "theta.coin-nodes.svc.cluster.local",
        "port": 16888
    },
    "log": {
        "level": "debug"
    },
    "blockchain": {
        "network_id": "mainnet"
    },
    "accounting": {
        "coinmarketcap_api_key": "COINMARKETCAP_API_KEY",
        "wallet_addresses": [
            "2416",
            "3822"
        ]
    },
    "redis": {
        "enabled": true,
        "isCluster": false,
        "host": "__THETACLIARG_REDIS_ENDPOINT__",
        "port": 6379,
        "family": 4,
        "db": 0
    }
```

I'm a bit stuck, is there anything I am doing wrong?

**Comment by giovannirco** [comment]
I actually think this is an issue with the MongoDB module, I will try to dive into this but I appreciate some guidance :D

**Comment by giovannirco** [comment]
This has been fixed by the last commits made on master
