### ISSUE TITLE
is there an upgrade for theta explorer?

### ISSUE THREAD

**Issue by voltagebots** [thetatoken/theta-infrastructure-ledger-explorer#39]
We just recently upgraded the theta coin-nodes to v=3.3.0.

However, we noticed the explorer-crawler component logs this after the coin-node upgrade:

**`Cannot read property 'length' of undefined | stack: TypeError: Cannot read property 'length' of undefined`**
```
 at /home/node/theta-infrastructure-ledger-explorer/backend/crawler/jobs/read-block.js:216:53
    at tryCatcher (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/node/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
```

is there a particular commit the explorer should be upgraded to accomodate this new version for the coin-nodes?

**Comment by voltagebots** [comment]
cc: @jieyilong

**Comment by voltagebots** [comment]
clsoing this: it had to do. with the crawler not able to fetch the height from the node.
