### ISSUE TITLE
Crawler doesn't transfer block into db

### ISSUE THREAD

**Issue by erzqk** [thetatoken/theta-infrastructure-ledger-explorer#43]
I run all components in a containers (node, crawler, backend-api, mongodb)
Crawler get an error: **Cannot read properties of undefined (reading 'length') | stack: TypeError: Cannot read properties of undefined (reading 'length')**

Part of log:

```
4/20/2022, 9:54:11 AM[log] Start a new crawler progress
4/20/2022, 9:54:11 AM[log] progressInfo: {"height":15031999,"count":0}
4/20/2022, 9:54:11 AM[log] DB transaction count progress: 0
4/20/2022, 9:54:11 AM[log] crawledBlockHeightProgress:  15031999
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetPendingTransactions","params":[],"id":"aIieaX40"}
[Debug]{"jsonrpc":"2.0","id":"aIieaX40","result":{"tx_hashes":["0xcd6d1f6d079eac08c37ba98beaf39d80859ed0817237f04ab08945a876387d06","0x6046d2659026b02ce83895547cd5b874f12a009477d36dae1d9f5f22045e335a","0x5b6494f9ddd411e69cec852f53fabc32293ebc635e7c6e5e6632ba29cd92417b"]}}

[Debug] ____
4/20/2022, 9:54:11 AM[log] Number of upsert PENDING transactions: 1
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetStatus","params":[],"id":"r0ZKc5Aa"}
[Debug]{"jsonrpc":"2.0","id":"r0ZKc5Aa","result":{"address":"0xA130C86b85e2cF8801c81b2b3FEcCEDd0D77425c","chain_id":"mainnet","peer_id":"0xA130C86b85e2cF8801c81b2b3FEcCEDd0D77425c","latest_finalized_block_hash":"0x7208ee1506f4d17f47ab53a9bd9ed3f66809d5308ceabb7c5ae3916310147cf9","latest_finalized_block_height":"15040716","latest_finalized_block_time":"1650448439","latest_finalized_block_epoch":"15126647","current_epoch":"15126649","current_height":"15040716","current_time":"1650448451","syncing":false,"genesis_block_hash":"0xd8836c6cf3c3ccea0b015b4ed0f9efb0ffe6254db793a515843c9d0f68cbab65"}}

[Debug] ____
4/20/2022, 9:54:11 AM[log] Latest block height: 15040716
4/20/2022, 9:54:11 AM[log] DB block height progress: 15031999
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetBlockByHeight","params":[{"height":"15032000","include_eth_tx_hashes":true}],"id":"kxz8kGDx"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetVcpByHeight","params":[{"height":"15032000"}],"id":"m8xinUwN"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetGcpByHeight","params":[{"height":"15032000"}],"id":"wOVeAe8r"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetEenpByHeight","params":[{"height":"15032000"}],"id":"8GpLEJlk"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetStakeRewardDistributionByHeight","params":[{"height":"15032000"}],"id":"y5Ohsl4Y"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetBlockByHeight","params":[{"height":"15032001","include_eth_tx_hashes":true}],"id":"LrbCneDz"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetVcpByHeight","params":[{"height":"15032001"}],"id":"chhrI3Ia"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetGcpByHeight","params":[{"height":"15032001"}],"id":"WG34cIb0"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetEenpByHeight","params":[{"height":"15032001"}],"id":"Oo6YpTW5"}
[Debug] ____
[Debug] Http request: {"host":"127.0.0.1","port":16888,"method":"POST","path":"/rpc","headers":{"Content-Type":"application/json"}} {"jsonrpc":"2.0","method":"theta.GetStakeRewardDistributionByHeight","params":[{"height":"15032001"}],"id":"AlBmVzq8"}
[Debug]{"jsonrpc":"2.0","id":"kxz8kGDx","result":{}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"y5Ohsl4Y","result":{"BlockHashStakeRewardDistributionRuleSetPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"LrbCneDz","result":{}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"wOVeAe8r","result":{"BlockHashGcpPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"8GpLEJlk","result":{"BlockHashEenpPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"m8xinUwN","result":{"BlockHashVcpPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"AlBmVzq8","result":{"BlockHashStakeRewardDistributionRuleSetPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"WG34cIb0","result":{"BlockHashGcpPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"Oo6YpTW5","result":{"BlockHashEenpPairs":[]}}

[Debug] ____
[Debug]{"jsonrpc":"2.0","id":"chhrI3Ia","result":{"BlockHashVcpPairs":[]}}

[Debug] ____
4/20/2022, 9:54:11 AM[log] Query block info takes: 7 ms
4/20/2022, 9:54:11 AM[error] Cannot read properties of undefined (reading 'length') | stack: TypeError: Cannot read properties of undefined (reading 'length')
    at /theta-infrastructure-ledger-explorer/backend/crawler/jobs/read-block.js:227:53
    at tryCatcher (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/theta-infrastructure-ledger-explorer/backend/crawler/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (node:internal/timers:466:21)
```

My config for crawler:

```
{
    "mongo": {
        "uri": "",
        "address": "127.0.0.1",
        "port": 27017,
        "dbName": "theta"
    },
    "node": {
        "address": "127.0.0.1",
        "port": 16888
    },
    "log": {
        "level": "debug"
    },
    "blockchain": {
        "networkId": "mainchain",
        "startHeight": 1
    },
    "accounting": {
        "coinmarketcapApiKey": "COINMARKETCAP_API_KEY",
        "walletAddresses": [
            "2416",
            "3822"
        ]
    },
    "redis": {
        "enabled": false,
        "isCluster": false,
        "host": "127.0.0.1",
        "port": 6379,
        "password": "",
        "family": 4,
        "db": 0
    },
    "nodeCache": {
        "enabled": false
    },
    "maxBlockPerCrawl": 2,
    "retrieveTokenStartHeight": 0,
    "defaultThetaChainID": "mainnet"
```

If i try to GET, block is not found
```
curl 127.0.0.1:8443/api/block/15031999 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    68  100    68    0     0   9714      0 --:--:-- --:--:-- --:--:-- 11333
{
  "type": "error_not_found",
  "error": {
    "cause": {},
    "isOperational": true
  }
}
```

I also tried run all components at my linux local machine and have same problem.

How can i fix this?

**Comment by erzqk** [comment]
Changes startheight to 15040000 (snapshot from 20.04.2022).
Erased MongoDB's data directory and this error resolved.
