### ISSUE TITLE
Unhandled rejection Error: No progress record

### ISSUE THREAD

**Issue by erzqk** [thetatoken/theta-infrastructure-ledger-explorer#44]
Hi, im trying to send request to explorer
`curl "127.0.0.1:8443/api/blocks/top_blocks?pageNumber=1&limit=1"`
and have no I don't get a response from this
tried inspect logs of explorer-backend and saw this
```
Mongo connection succeeded
socket.IO api running on port. 2096
rest api running on port. 8443
Unhandled rejection Error: No progress record
    at /theta-infrastructure-ledger-explorer/backend/mongo-db/progress-dao.js:65:20
    at /theta-infrastructure-ledger-explorer/backend/mongo-db/mongo-client.js:124:5
    at /theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/utils.js:704:5
    at executeCallback (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/operations/execute_operation.js:65:7)
    at handleCallback (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/utils.js:109:55)
    at /theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/operations/find_one.js:31:9
    at /theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/utils.js:704:5
    at /theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/cursor.js:256:9
    at /theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:746:9
    at handleCallback (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:32:5)
    at /theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:690:38
    at Cursor._endSession (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:404:7)
    at _setCursorNotifiedImpl (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:699:10)
    at setCursorNotified (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:690:3)
    at done (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:465:16)
    at queryCallback (/theta-infrastructure-ledger-explorer/backend/explorer-api/node_modules/mongodb/lib/core/cursor.js:510:20)
```
MongoDB and crawler work's fine
What i should do with this issue?

**Comment by zhenyang-sliver** [comment]
If there're some records in the mongoDB, can you check the dbName in both config files(crawler and explorer-api) are the same? 
```
"mongo": {
        "uri": "",
        "address": "localhost",
        "port": 27017,
        "dbName": "YOUR_DB_NAME"
    },
```

**Comment by erzqk** [comment]
@zhenyang-sliver Oh, you are right, my dbname has a different name with a explorer backend.
Now it's work, ty so much.
